/****************
 EVENTS
 ****************/

export const FETCH_EVENT_LIST_PENDING = 'FETCH_EVENT_LIST_PENDING';
export const FETCH_EVENT_LIST_SUCCESS = 'FETCH_EVENT_LIST_SUCCESS';
export const FETCH_EVENT_LIST_FAILURE = 'FETCH_EVENT_LIST_FAILURE';

export const CHANGE_ACTIVE_EVENT = 'CHANGE_ACTIVE_EVENT';

export const FETCH_EVENT_DETAIL_PENDING = 'FETCH_EVENT_DETAIL_PENDING';
export const FETCH_EVENT_DETAIL_SUCCESS = 'FETCH_EVENT_DETAIL_SUCCESS';
export const FETCH_EVENT_DETAIL_FAILURE = 'FETCH_EVENT_DETAIL_FAILURE';

export const APPLY_VENUE_FILTER = 'APPLY_VENUE_FILTER';
export const APPLY_TYPE_FILTER = 'APPLY_TYPE_FILTER';

export const APPLY_SEARCH_FILTER = 'APPLY_SEARCH_FILTER';

